# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fs_pb2 as fs__pb2


class FileServerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.filename = channel.unary_unary(
                '/FileServer/filename',
                request_serializer=fs__pb2.fs.SerializeToString,
                response_deserializer=fs__pb2.fs.FromString,
                )
        self.upload = channel.stream_unary(
                '/FileServer/upload',
                request_serializer=fs__pb2.Chunk.SerializeToString,
                response_deserializer=fs__pb2.Reply.FromString,
                )
        self.download = channel.unary_stream(
                '/FileServer/download',
                request_serializer=fs__pb2.Request.SerializeToString,
                response_deserializer=fs__pb2.Chunk.FromString,
                )
        self.getServerStats = channel.unary_unary(
                '/FileServer/getServerStats',
                request_serializer=fs__pb2.EMPTY.SerializeToString,
                response_deserializer=fs__pb2.stats.FromString,
                )


class FileServerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def filename(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getServerStats(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'filename': grpc.unary_unary_rpc_method_handler(
                    servicer.filename,
                    request_deserializer=fs__pb2.fs.FromString,
                    response_serializer=fs__pb2.fs.SerializeToString,
            ),
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=fs__pb2.Chunk.FromString,
                    response_serializer=fs__pb2.Reply.SerializeToString,
            ),
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=fs__pb2.Request.FromString,
                    response_serializer=fs__pb2.Chunk.SerializeToString,
            ),
            'getServerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.getServerStats,
                    request_deserializer=fs__pb2.EMPTY.FromString,
                    response_serializer=fs__pb2.stats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileServer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def filename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileServer/filename',
            fs__pb2.fs.SerializeToString,
            fs__pb2.fs.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileServer/upload',
            fs__pb2.Chunk.SerializeToString,
            fs__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/download',
            fs__pb2.Request.SerializeToString,
            fs__pb2.Chunk.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getServerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileServer/getServerStats',
            fs__pb2.EMPTY.SerializeToString,
            fs__pb2.stats.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
